const certificates = [
  {
    name: 'The Fundamentals Of GDPR',
    image: '',
    instructor: "Pat O'Boyle",
    institution: 'HSELand',
    conclusion: 'May 2025',
    type: 'Certificate',
    sharingLink:
      'https://www.hseland.ie/ekp/servlet/ekp/PRINTCERT?PX=N&USERID=ekp000521117&SK=0&AWARDID=EKP-9482-8944-7876-2211&ACTION=PRINTCERT',
    area: 'Healthcare',
  },
  {
    name: 'NLW Unite, Reactjs - 2024',
    image: '',
    workload: '5h',
    instructor: 'Diego Fernandes',
    institution: 'Rocketseat',
    conclusion: 'June 2024',
    type: 'Certificate',
    score: '',
    sharingLink:
      'https://app.rocketseat.com.br/certificates/d77ade0c-29de-4395-b23a-878c7a3f150d',
    area: 'IT',
  },
  {
    name: 'Human Rights-Based Approach In Health And Social Care - Module 1',
    image: '',
    instructor: `Dr. Niamh O'Rourke`,
    institution: 'HSELand',
    conclusion: 'May 2024',
    type: 'Certificate',
    sharingLink:
      'https://www.hseland.ie/ekp/servlet/ekp/PRINTCERT?PX=N&USERID=ekp000521117&SK=0&AWARDID=EKP-3317-0400-1812-5215&ACTION=PRINTCERT',
    area: 'Healthcare',
  },
  {
    name: 'Human Rights-Based Approach In Health And Social Care - Module 2',
    image: '',
    instructor: `Dr. Niamh O'Rourke`,
    institution: 'HSELand',
    conclusion: 'May 2024',
    type: 'Certificate',
    sharingLink:
      'https://www.hseland.ie/ekp/servlet/ekp/PRINTCERT?PX=N&USERID=ekp000521117&SK=0&AWARDID=EKP-3395-2226-5332-1723&ACTION=PRINTCERTCTION=PRINTCERT',
    area: 'Healthcare',
  },
  {
    name: 'Human Rights-Based Approach In Health And Social Care - Module 3',
    image: '',
    instructor: `Dr. Niamh O'Rourke`,
    institution: 'HSELand',
    conclusion: 'May 2024',
    type: 'Certificate',
    sharingLink:
      'https://www.hseland.ie/ekp/servlet/ekp/PRINTCERT?PX=N&USERID=ekp000521117&SK=0&AWARDID=EKP-3395-8784-7595-7832&ACTION=PRINTCERT',
    area: 'Healthcare',
  },
  {
    name: 'Human Rights-Based Approach In Health And Social Care - Module 4',
    image: '',
    instructor: `Dr. Niamh O'Rourke`,
    institution: 'HSELand',
    conclusion: 'April 2024',
    type: 'Certificate',
    sharingLink:
      'https://www.hseland.ie/ekp/servlet/ekp/PRINTCERT?PX=N&USERID=ekp000521117&SK=0&AWARDID=EKP-2250-7305-7656-8374&ACTION=PRINTCERT',
    area: 'Healthcare',
  },
  {
    name: 'React Fundamentals',
    image: '',
    workload: '6h',
    instructor: 'Diego Fernandes',
    institution: 'Rocketseat',
    conclusion: 'April 2024',
    type: 'Certificate',
    sharingLink:
      'https://app.rocketseat.com.br/certificates/dd33bbf9-1660-4986-a339-1e042564f8d2',
    area: 'IT',
  },
  {
    name: 'Dignity At Work (Revised 2022)',
    image: '',
    institution: 'HSELand',
    conclusion: 'February 2023',
    type: 'Certificate',
    sharingLink:
      'https://www.hseland.ie/ekp/servlet/ekp/PRINTCERT?PX=N&USERID=ekp000521117&SK=0&AWARDID=EKP-1194-8775-1671-1133&ACTION=PRINTCERT',
    area: 'Healthcare',
  },
  {
    name: 'Manual Handling And People Handling E-Learning Theory Module',
    image: '',
    institution: 'HSELand',
    conclusion: 'February 2023',
    type: 'Certificate',
    sharingLink:
      'https://www.hseland.ie/ekp/servlet/ekp/PRINTCERT?PX=N&USERID=ekp000521117&SK=0&AWARDID=EKP-1137-9016-7422-5685&ACTION=PRINTCERT',
    area: 'Healthcare',
  },
  {
    name: 'Safeguarding Adults At Risk Of Abuse',
    image: '',
    institution: 'HSELand',
    conclusion: 'February 2023',
    type: 'Certificate',
    sharingLink:
      'https://www.hseland.ie/ekp/servlet/ekp/PRINTCERT?PX=N&USERID=ekp000521117&SK=0&AWARDID=EKP-1155-8571-5825-6061&ACTION=PRINTCERT',
    area: 'Healthcare',
  },
  {
    name: 'AMRIC Hand Hygiene',
    image: '',
    institution: 'HSELand',
    conclusion: 'February 2023',
    type: 'Certificate',
    sharingLink:
      'https://www.hseland.ie/ekp/servlet/ekp/PRINTCERT?PX=N&USERID=ekp000521117&SK=0&AWARDID=EKP-1159-1469-6557-8057&ACTION=PRINTCERT',
    area: 'Healthcare',
  },
  {
    name: 'AMRIC Basics Of Infection Prevention And Control',
    image: '',
    institution: 'HSELand',
    conclusion: 'February 2023',
    type: 'Certificate',
    sharingLink:
      'https://www.hseland.ie/ekp/servlet/ekp/PRINTCERT?PX=N&USERID=ekp000521117&SK=0&AWARDID=EKP-1225-2798-9735-9142&ACTION=PRINTCERT',
    area: 'Healthcare',
  },
  {
    name: 'Putting On And Taking Off PPE In Community Healthcare Settings',
    image: '',
    institution: 'HSELand',
    conclusion: 'February 2023',
    type: 'Certificate',
    sharingLink:
      'https://www.hseland.ie/ekp/servlet/ekp/PRINTCERT?PX=N&USERID=ekp000521117&SK=0&AWARDID=EKP-1240-4239-2313-3558&ACTION=PRINTCERT',
    area: 'Healthcare',
  },
  {
    name: 'Introduction To Front-End Development',
    image: '',
    institution: 'Meta',
    conclusion: 'November 2022',
    type: 'Certificate',
    sharingLink: 'https://coursera.org/verify/GNDUR679YQ8F',
    area: 'IT',
  },
  {
    name: 'An Introduction To Children First',
    image: '',
    institution: 'HSELand',
    conclusion: 'May 2022',
    type: 'Certificate',
    area: 'Healthcare',
  },
  {
    name: 'JavaScript',
    image: '',
    workload: '40h',
    instructor: 'Gustavo Guanabara',
    institution: 'Curso em Video',
    conclusion: 'March 2022',
    type: 'Certificate',
    score: '70%',
    sharingLink:
      'https://www.cursoemvideo.com/certificates/certificado/?course_id=27745&cert-nonce=da8ab5799e',
    area: 'IT',
  },
  {
    name: 'Spring React Week - DS Movie',
    image: '',
    workload: '16h',
    instructor: 'Nelio Alves',
    institution: 'DevSuperior',
    conclusion: 'January 2022',
    type: 'Certificate',
    area: 'IT',
  },
  {
    name: 'HTML 5 And CSS 3',
    image: '',
    workload: '40h',
    instructor: 'Gustavo Guanabara',
    institution: 'Curso em Video',
    conclusion: 'January 2022',
    type: 'Certificate',
    score: '70%',
    sharingLink:
      'https://www.cursoemvideo.com/certificates/certificado/?course_id=25557&cert-nonce=0af0966458',
    area: 'IT',
  },
  {
    name: 'Spring React Week - DS Vendas',
    image: '',
    workload: '16h',
    instructor: 'Nelio Alves',
    institution: 'DevSuperior',
    conclusion: 'November 2021',
    type: 'Certificate',
    area: 'IT',
  },
  {
    name: 'C# Complete 2020 Oriented Object Programming',
    image: '',
    workload: '35h',
    instructor: 'Nelio Alves',
    institution: 'Udemy',
    conclusion: 'April 2020',
    type: 'Certificate',
    sharingLink:
      'https://www.udemy.com/certificate/UC-f2c12ab7-2d3e-40be-8d6b-3cfb142bdc0b/',
    area: 'IT',
  },
  {
    name: 'Algorithms And Programming Logic',
    image: '',
    workload: '40h',
    instructor: 'Gustavo Guanabara',
    institution: 'Curso em Video',
    conclusion: 'March 2020',
    type: 'Certificate',
    score: '80%',
    area: 'IT',
  },
  {
    name: 'Automatic Tests + Complete Software Testing Course',
    image: '',
    workload: '5h',
    instructor: 'Gustavo Farias',
    institution: 'Udemy',
    conclusion: 'July 2019',
    type: 'Certificate',
    sharingLink: 'https://www.udemy.com/certificate/UC-VCENBNNY/',
    area: 'IT',
  },
  {
    name: 'Word 2016',
    image: '',
    workload: '40h',
    instructor: 'Gustavo Guanabara',
    institution: 'Curso em video',
    conclusion: 'July 2019',
    type: 'Certificate',
    score: '80%',
    area: 'Administrative',
  },
  {
    name: 'Java',
    image: '',
    workload: '40h',
    instructor: 'Gustavo Guanabara',
    institution: 'Curso em Video',
    conclusion: 'January 2019',
    type: 'Certificate',
    score: '100%',
    area: 'IT',
  },
  {
    name: 'SAP ERP Intelligence',
    image: '',
    workload: '20h',
    instructor: 'Roberto Evison',
    institution: 'MDL Consulting',
    conclusion: 'August 2018',
    type: 'Certificate',
    area: 'IT',
  },
  {
    name: 'Mind Mapping',
    image: '',
    workload: '8h',
    instructor: 'Dr. Tadeo Feijao',
    conclusion: 'September 2016',
    type: 'Certificate',
    area: 'Personal',
  },
  {
    name: 'Hardware - Computer Assembly And Maintenance',
    image: '',
    workload: '57h',
    instructor: '',
    institution: 'CEBRAC',
    conclusion: 'April 2009',
    type: 'Certificate',
    score: '10.0',
    area: 'IT',
  },
  {
    name: 'Administrative Development',
    image: '',
    workload: '50h',
    institution: 'CEBRAC',
    conclusion: 'July 2008',
    type: 'Certificate',
    score: '10.0',
    area: 'Administrative',
  },
  {
    name: 'Personal Development',
    image: '',
    workload: '50h',
    institution: 'CEBRAC',
    conclusion: 'July 2008',
    type: 'Certificate',
    score: '10.0',
    area: 'Personal',
  },
  {
    name: 'Technological Development',
    image: '',
    workload: '47h',
    institution: 'CEBRAC',
    conclusion: 'July 2008',
    type: 'Certificate',
    score: '9.5',
    area: 'IT',
  },
];

export function GetCertificatesByUserToInsert(userId: string) {
  const certificatesByUserToInsert = certificates.map(certificate => ({
    ...certificate,
    user_ID: userId,
    image: `uploads/certificates/${certificate.name
      .replace(/\s+/g, '-')
      .replace(/#/g, 'Sharp')
    }.jpeg`,
  }));

  return certificatesByUserToInsert;
}
